debug: true
verbose: true
copy: true
aniDb:
  username: TestUser
  password: SecurePassword
  maxFileSearchRetries: 5
  fileSearchCooldownMinutes: 300
sources:
  - \\SERVEY\unsorted
libraryPaths:
  - \\SERVEY\anime1
  - \\SERVEY\anime2
destination:
  path: \\SERVERY\anime2
  tvPath: tv
  moviePath: mov
  fragmentSeries: false
  format: ""{animeRomaji}\\{animeRomaji} - {episodeNumber}{'v'fileVersion} - {episodeEnglish...} [{groupShort}][{resolution}][{videoCodec}][{crc32}]"