name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  Test:
    needs: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    
  Report:
    needs: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: AniSort Tests
          path: test-results.xml
          reporter: dotnet-trx
    
