name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: AniDbSharp Unit Tests
      run: dotnet test AniDbSharpTests --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name: AniSort.Core Unit Tests
      run: dotnet test AniSort.CoreTests --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name: Report AniDbSharp Unit Tests
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: AniDbSharp Unit Tests
        path: AniDbSharpTest/TestResults/test-results.trx
        reporter: dotnet-trx
    - name: Report AniSort.Core Unit Tests
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: AniSort.Core Unit Tests
        path: AniSort.CoreTests/TestResults/test-results.trx
        reporter: dotnet-trx
    
