name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  Test:
    needs: Build
    runs-on: ubuntu-latest
    
    steps:
#    - name: Test
#      run: dotnet test --verbosity normal
    - name: Anisort.Core Tests
      uses: zyborg/dotnet-tests-report@v1.4.4
      with:
        project_path: Anisort.CoreTests
        report_name: AniSort.Core Tests
        no_build: true
    - name: AniDbSharp Tests
      uses: zyborg/dotnet-tests-repot@v1.4.4
      with:
        project_path: AniDbSharpTests
        report_name: AniDbSharp Tests
        no_build: true
